'use client';
import { useEffect, useState } from 'react';
const empty={category:'Diwali Sales 2026',name:'',image:'',content:'Pkt',actualPrice:'',price:''};
export default function Admin(){
 const [password,setPassword]=useState(''); const [logged,setLogged]=useState(false); const [products,setProducts]=useState([]); const [form,setForm]=useState(empty); const [message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/products'); setProducts(await r.json())}
 function login(e){e.preventDefault(); if(password){setLogged(true);sessionStorage.setItem('yg_admin',password);}}
 useEffect(()=>{const p=sessionStorage.getItem('yg_admin');if(p){setPassword(p);setLogged(true)}},[]); useEffect(()=>{if(logged)load()},[logged]);
 async function save(e){e.preventDefault();setMessage(''); const r=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json','x-admin-password':password},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setMessage(d.error||'Could not save');return}setMessage('Product saved successfully.');setForm(empty);load();}
 async function del(id){if(!confirm('Delete this product?'))return;await fetch('/api/products',{method:'DELETE',headers:{'Content-Type':'application/json','x-admin-password':password},body:JSON.stringify({id})});load()}
 if(!logged)return <main className="admin-shell"><div className="admin-card login"><h1>Admin</h1><div className="notice">Enter the admin password to manage products.</div><form onSubmit={login}><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></div><div className="admin-actions"><button className="btn btn-red">Sign in</button></div></form></div></main>;
 return <main className="admin-shell"><div className="admin-card"><h1>Product Admin</h1>{message&&<div className="success">{message}</div>}<form onSubmit={save}><div className="admin-grid"><div className="field"><label>Category</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div className="field"><label>Product Name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Image URL</label><input placeholder="https://..." value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></div><div className="field"><label>Content</label><input required value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></div><div className="field"><label>Actual Price</label><input type="number" min="0" value={form.actualPrice} onChange={e=>setForm({...form,actualPrice:e.target.value})}/></div><div className="field"><label>Price</label><input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></div></div><div className="admin-actions"><button className="btn btn-red">Add Product</button><button type="button" className="btn btn-outline" onClick={()=>{sessionStorage.removeItem('yg_admin');setLogged(false)}}>Sign out</button></div></form><h2>Current Products</h2><table className="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Actual</th><th>Price</th><th>Action</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.category}</td><td>₹{p.actualPrice}</td><td>₹{p.price}</td><td><button className="delete" onClick={()=>del(p.id)}>Delete</button></td></tr>)}</tbody></table></div></main>
}
